### ISSUE TITLE
Error Preventing Compiling

### ISSUE THREAD

**Issue by sitver** [kwkhaw/Layer-Parse-iOS-Swift-Example#5]
When I go to build in Xcode, I get an error around line 63 of the conversationViewController, pertaining to the NSAttributedString for the date (Screenshot below).

Any ideas?
<img width="616" alt="screen shot 2015-07-20 at 1 27 31 am" src="https://cloud.githubusercontent.com/assets/4080251/8770607/b898c3b2-2e82-11e5-96df-298bb614333b.png">

**Comment by kwkhaw** [comment]
Hi @sitver, may I know what is your XCode version?

**Comment by sitver** [comment]
Xcode 7 beta 3. OSX El Capitan

**Comment by kwkhaw** [comment]
Ah, I see. I have pushed a new changes, which should fix the issue you encountered. Commit 7d89ffffdda3cebe03c89a0f79de9b27b96735f1

By the way, actually I also created the branch `swift2` few days ago (which also has the fix for your error). Probably you can switch to that branch to try it out.

I will close the issue for now. Please let me know if you still encounter the error.

Thanks for reporting the issue.

**Comment by kwkhaw** [comment]
@sitver I recalled that I encountered the issue which is similar to this (https://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9)) when connecting to Layer server, which I fixed in `swift2` branch by adding a workaround in the Info.plist. So, you have to use `swift2` branch if you are using Xcode 7, else it won't work.

**Comment by sitver** [comment]
Thanks
