### ISSUE TITLE
Conversation can't be selected / opened!

### ISSUE THREAD

**Issue by Deviz** [kwkhaw/Layer-Parse-iOS-Swift-Example#6]
After i select conversation and go back to conversation list, and then close app with home button and open app again, I can't select conversation. This issue is also mentioned in the last comment here:
https://github.com/kwkhaw/Layer-Parse-iOS-Swift-Example/issues/2

**Comment by kwkhaw** [comment]
Ah... that's bad... seems like the issue introduced by the fix is worse than the original issue. 😓
I debugged a little bit, and noticed that this happened because NSCache is cleared whenever the app is moved to background.
I think I have few options:
1. Find a way to prevent the cached users from being cleared or store it to persistent storage and restore again whenever the app become active again.
2. Apply another workaround in "didSelectConversation" delegate method to query the users from Parse again whenever there are unresolved participants.
3. Fix the original issue in Atlas-iOS. Currently if `nil` is returned from `conversationViewController(_:participantForIdentifier)`, it will crash in Atlas.
I will try to do it tomorrow.
By the way, @Deviz thanks for reporting the issue. :-)

**Comment by Deviz** [comment]
@kwkhaw thanks for replying. Yeah, because this bug totally hinders any meaningful conversation between users. Would using reloadCellForConversation everytime not be a quickfix to this problem or is it not long-term enough?

**Comment by kwkhaw** [comment]
@Deviz what I noticed in issue #2 is Atlas crashed when we return `nil` in `func conversationViewController(conversationViewController: ATLConversationViewController, participantForIdentifier participantIdentifier: String) -> ATLParticipant?`, thus I added the workaround (which leads to this issue).
I updated Atlas to 0.10.0, issue #2 no longer happened without the workaround. So, I just simply removed the workaround. Commit c92f3b4a1b91ebf1c6fc839c1bd096d3f83da325 should fix this issue.
Thanks ya. :-)
